#ifndef kode_widgets_included
#define kode_widgets_included
//----------------------------------------------------------------------

#include "gui/kode_widget.h"

#include "gui/widgets/_template_widget.h"

#include "gui/widgets/kode_background_widget.h"
#include "gui/widgets/kode_border_widget.h"
#include "gui/widgets/kode_button_widget.h"
#include "gui/widgets/kode_button_row_widget.h"
#include "gui/widgets/kode_circular_waveform_widget.h"
#include "gui/widgets/kode_color_widget.h"
#include "gui/widgets/kode_curve_widget.h"
#include "gui/widgets/kode_drag_value_widget.h"
#include "gui/widgets/kode_graph_widget.h"
#include "gui/widgets/kode_grid_widget.h"
#include "gui/widgets/kode_group_widget.h"
#include "gui/widgets/kode_group_box_widget.h"
#include "gui/widgets/kode_header_widget.h"
#include "gui/widgets/kode_image_widget.h"
#include "gui/widgets/kode_image_strip_widget.h"
#include "gui/widgets/kode_keyboard_widget.h"
#include "gui/widgets/kode_knob_widget.h"
#include "gui/widgets/kode_knob2_widget.h"
#include "gui/widgets/kode_knob3_widget.h"
#include "gui/widgets/kode_knob4_widget.h"
#include "gui/widgets/kode_menu_widget.h"
#include "gui/widgets/kode_menu_item_widget.h"
#include "gui/widgets/kode_modmatrix_widget.h"
#include "gui/widgets/kode_overlay_widget.h"
#include "gui/widgets/kode_pages_widget.h"
#include "gui/widgets/kode_plot_widget.h"
#include "gui/widgets/kode_range_slider_widget.h"
#include "gui/widgets/kode_sa_header_widget.h"
#include "gui/widgets/kode_scroll_bar_widget.h"
#include "gui/widgets/kode_scroll_box_widget.h"
#include "gui/widgets/kode_selector_widget.h"
#include "gui/widgets/kode_size_box_widget.h"
#include "gui/widgets/kode_sizer_widget.h"
#include "gui/widgets/kode_slider_widget.h"
#include "gui/widgets/kode_slider_bank_widget.h"
#include "gui/widgets/kode_switch_widget.h"
#include "gui/widgets/kode_symbol_widget.h"
#include "gui/widgets/kode_tabs_widget.h"
#include "gui/widgets/kode_text_widget.h"
#include "gui/widgets/kode_text_box_widget.h"
#include "gui/widgets/kode_text_edit_widget.h"
#include "gui/widgets/kode_timeline_widget.h"
#include "gui/widgets/kode_value_widget.h"
#include "gui/widgets/kode_value_graph_widget.h"
#include "gui/widgets/kode_waveform_widget.h"

//----------------------------------------------------------------------
#endif

