#ifndef s3_widgets_included
#define s3_widgets_included
//----------------------------------------------------------------------

//#include "gui/widgets/s3_widget_agg.h"
//#include "gui/widgets/s3_widget_bitmap.h"
//#include "gui/widgets/s3_widget_button.h"
//#include "gui/widgets/s3_widget_buttonrow.h"
//#include "gui/widgets/s3_widget_circular_waveform.h"
#include "gui/widgets/s3_widget_color.h"
#include "gui/widgets/s3_widget_dragvalue.h"
//#include "gui/widgets/s3_widget_graph.h"
//#include "gui/widgets/s3_widget_grid.h"
//#include "gui/widgets/s3_widget_group.h"
//#include "gui/widgets/s3_widget_groupbox.h"
//#include "gui/widgets/s3_widget_imagestrip.h"
//#include "gui/widgets/s3_widget_imgknob.h"
//#include "gui/widgets/s3_widget_keyboard.h"
//#include "gui/widgets/s3_widget_knob.h"
//#include "gui/widgets/s3_widget_knob2.h"
//#include "gui/widgets/s3_widget_menu.h"
//#include "gui/widgets/s3_widget_menuitem.h"
//#include "gui/widgets/s3_widget_modmatrix.h"
//#include "gui/widgets/s3_widget_nodes.h"
#include "gui/widgets/s3_widget_number.h"
//#include "gui/widgets/s3_widget_overlay.h"
//#include "gui/widgets/s3_widget_pages.h"
//#include "gui/widgets/s3_widget_panel.h"
//#include "gui/widgets/s3_widget_plot.h"
//#include "gui/widgets/s3_widget_popup.h"
//#include "gui/widgets/s3_widget_scrollbar.h"
//#include "gui/widgets/s3_widget_scrollbox.h"
//#include "gui/widgets/s3_widget_selector.h"
//#include "gui/widgets/s3_widget_sizer.h"
//#include "gui/widgets/s3_widget_slider.h"
//#include "gui/widgets/s3_widget_sliderbank.h"
#include "gui/widgets/s3_widget_string.h"
//#include "gui/widgets/s3_widget_switch.h"
//#include "gui/widgets/s3_widget_symbol.h"
//#include "gui/widgets/s3_widget_tabs.h"
#include "gui/widgets/s3_widget_text.h"
//#include "gui/widgets/s3_widget_textarea.h"
//#include "gui/widgets/s3_widget_textedit.h"
//#include "gui/widgets/s3_widget_timeline.h"
#include "gui/widgets/s3_widget_value.h" // empty
//#include "gui/widgets/s3_widget_waveform.h"

//----------------------------------------------------------------------
#endif
